void basic_loop(); // function header
void leetcode_find_max();
void leetcode_shuffle_two_arrays();
void leetcode_bubble_sort();
void basic_vector_usage();
void basic_pointer_usage();
void basic_cplusplus_operators();
void leetcode_sorting_two_sorted_lists();
void basic_call_by_reference();
void basic_string_usage();
void leetcode_letters_histogram();
void basic_struct_usage();
void basic_dynamic_memory_allocation();
void leetcode_remove_duplicate_from_sorted_array();
void basic_pair_usage();
void leetcode_fibonacii_seq();
void basic_cstd_pair_unorderedmap_map();
void leetcode_two_sum();
void leetcode_lonest_substring_without_repeating();
void basic_sort_usage();
void leetcode_alternating_strings();
void basic_digit_representation();
void leetcode_bits_reversal();
void leetcode_revert_integer();
void leetcode_even_odd_diff();
void basic_binary_concept();
void leetcode_functionParsing();
void basic_binaryTree_BF_create();

